import Head from 'next/head'
import Image from '../components/image/image'
import styles from '../styles/Home.module.css'
import polaroid from '../public/polaroid.png'
import Tile from '../components/tile/tile'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>julia website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.headline}>
          hello
        </h1>
        <p>I am the coolest</p>
        <Image alt="Polaroid image of Julia and Savanna" src={polaroid} width={753} height={1209} />
        <div className={styles.tiles}>
          <Tile image={polaroid} headline="this is a picture." details='this is a picture someone took.' link={"test"} />
          <Tile image={polaroid} headline="this is a picture." details='this is a picture someone took.' link={"test"} />
          <Tile image={polaroid} headline="this is a picture." details='this is a picture someone took.' link={"test"} />
        </div>
      </main>
      <footer>

      </footer>
    </div>
  )
}




