import { useRouter } from 'next/router';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Tile from '../components/tile/tile';
import { useEffect, useState } from 'react';
import Post from '../types/Post';
import { addPost, loadPosts } from '../firebase';
import PayPal from '../components/paypal/paypal';
import { PayPalScriptProvider, PayPalButtons } from '@paypal/react-paypal-js';

export default function Home({ admin }: { admin: boolean }) {
	const [city, setCity] = useState('');
	useEffect(() => {
		fetch('https://ipinfo.io/geo?token=7abe1afad1fdd6').then((response) => {
			response.json().then((data) => {
				setCity(data.city);
			});
		});
	}, []);

	const [fact, setFact] = useState('');
	useEffect(() => {
		fetch('https://catfact.ninja/fact').then((response) => {
			response.json().then((data) => {
				setFact(data.fact);
			});
		});
	}, []);

	const [dogImage, setDogImage] = useState('');
	useEffect(() => {
		fetch('https://dog.ceo/api/breeds/image/random').then((response) => {
			response.json().then((data) => {
				setDogImage(data.message);
			});
		});
	}, []);

	const [link, setLink] = useState('');
	const router = useRouter();

	const add = () => {
		if (link) {
			addPost(link).then(() => {
				router.push(`/posts/${link}`);
			});
		}
	};

	const [posts, setPosts] = useState<Post[]>([]);

	useEffect(() => {
		loadPosts().then(setPosts);
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>julia website</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<PayPal />
			{/* <PayPalScriptProvider options={{ 'client-id': 'test' }}>
				<PayPalButtons style={{ layout: 'horizontal' }} />
			</PayPalScriptProvider> */}
			julia thanks you for visiting from {city}
			<main>
				<h1 className={styles.headline}>hello</h1>
				<p>I am the coolest</p>
				<div className={styles.tiles}>
					{posts.map((tile, index) => (
						<Tile
							key={index}
							image={tile.image}
							headline={tile.headline}
							details={tile.details}
							link={'posts/' + tile.link}
						/>
					))}
				</div>
				{admin && (
					<>
						<input onChange={(event) => setLink(event.target.value)} type="text" value={link} />
						<button onClick={add}>add</button>
					</>
				)}
			</main>
			<footer></footer>
		</div>
	);
}
